### ISSUE TITLE
Knit unable to renew HDFS delegation token

### ISSUE THREAD

**Issue by ssabdb** [blaze/rambling#128]
I'm running knit with an HA kerberised cluster and not able to start an application. Other applications, eg spark, mapreduce, hive all work fine. 

I suspect something is wrong with the way knit is handling Kerberos/HA. The job does not even start.

```
import knit
knit.__version__
'0.2.4'
k = knit.Knit()
```

```
Results in:
18/06/01 15:28:35 INFO knit.Client$: Starting Application Master
18/06/01 15:28:36 INFO hdfs.DFSClient: Created HDFS_DELEGATION_TOKEN token 8599252 for XXXXXXXX on ha-hdfs:XXX03
18/06/01 15:28:37 INFO knit.Utils$: Setting Replication Factor to: 3
18/06/01 15:28:37 INFO knit.Utils$: Attemping upload of /home/XXXXXXXX/.conda/envs/dask-knit/lib/python3.5/site-packages/knit/java_libs/knit-1.0-SNAPSHOT.jar to /user/XXXXXXXX/.knitDeps
18/06/01 15:28:37 INFO impl.TimelineClientImpl: Timeline service address: http://XX:8188/ws/v1/timeline/
18/06/01 15:28:38 INFO knit.Client$: Submitting application application_1525508843598_162207
Py4JJavaError: An error occurred while calling t.start.
: org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1525508843598_162207 to YARN : Failed to renew token: Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:XXX03, Ident: (HDFS_DELEGATION_TOKEN token 8599252 for XXXXXXXX)
        at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:271)
        at io.continuum.knit.Client$.start(Client.scala:178)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by martindurant** [comment]
Unfortunately, the error above does not mean a huge amount to me, but you may be interested in being an early adopter of [skein](https://github.com/jcrist/skein), which is a ground-up rewrite of, and eventual replacement for `knit`. It has not yet been released, and documentation is lacking, but it should interact with hadoop services much more smoothly.

**Comment by jcrist** [comment]
dask-yarn has been rewritten, and should be more robust to different hadoop configurations. Please see the docs (https://dask-yarn.readthedocs.io/en/latest/) and new repo (https://github.com/dask/dask-yarn). Closing.
