### ISSUE TITLE
Tracking kerberos problems

### ISSUE THREAD

**Issue by martindurant** [blaze/rambling#67]
xref https://github.com/dask/dask-yarn/issues/17

**Comment by quartox** [comment]
This appears to be fixed for me with #71 
I am getting a new error, however, that I don't really understand. Let me know if we should move this to a new issue since it may not be kerberos related.

The job hangs after submitting the application and is killed by a keyboard interrupt after several minutes.

```
17/08/09 11:02:13 INFO impl.YarnClientImpl: Submitted application application_1498411385005_148572
^CTraceback (most recent call last):
  File "test.py", line 9, in <module>
    future.result()
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/distributed/client.py", line 118, in result
    self._result, raiseit=False, callback_timeout=timeout)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/distributed/utils.py", line 221, in sync
    e.wait(1000000)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
17/08/09 11:37:01 INFO impl.YarnClientImpl: Killed application application_1498411385005_148572
```

The hadoop logs:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.10.1-1.cdh5.10.1.p0.10/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/hadoop02/yarn/nm/filecache/39/knit-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17/08/09 11:02:19 INFO knit.ApplicationMaster$: Construct application master
17/08/09 11:02:20 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/09 11:02:20 INFO knit.ApplicationMaster$: Number of tokens: 2
17/08/09 11:02:21 INFO impl.NMClientAsyncImpl: Upper bound of the thread pool size is 500
17/08/09 11:02:21 INFO knit.ApplicationMaster$: Init application master
17/08/09 11:02:21 INFO knit.ApplicationMaster$: 0 containers still running, requesting 2
17/08/09 11:02:21 INFO knit.ApplicationMaster$: Add 2 containers
17/08/09 11:02:21 INFO knit.ApplicationMaster$: Request: 500 MB of RAM and 1 cores
17/08/09 11:02:21 INFO knit.ApplicationMaster$: Requested container resources: <memory:500, vCores:1>
17/08/09 11:02:21 INFO knit.ApplicationMaster$: Requested container ask: Capability[<memory:500, vCores:1>]Priority[0]
17/08/09 11:02:21 INFO knit.ApplicationMaster$: Requested container resources: <memory:500, vCores:1>
17/08/09 11:02:21 INFO knit.ApplicationMaster$: Requested container ask: Capability[<memory:500, vCores:1>]Priority[0]
17/08/09 11:02:23 INFO knit.ApplicationMaster$: Running command in container: $PYTHON_BIN $CONDA_PREFIX/bin/dask-worker --nprocs=1 --nthreads=1 --memory-limit=500000000 tcp://10.195.208.189:45683 > /tmp/worker-log.out 2> /tmp/worker-log.err
17/08/09 11:02:23 INFO knit.ApplicationMaster$: TOKEN ADDED: Kind: YARN_AM_RM_TOKEN, Service: 10.195.208.186:8030,10.195.208.187:8030, Ident: (org.apache.hadoop.yarn.security.AMRMTokenIdentifier@7a77e921)
17/08/09 11:02:23 INFO knit.ApplicationMaster$: TOKEN ADDED: Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:nameservice1, Ident: (token for jlord: HDFS_DELEGATION_TOKEN owner=jlord@AD.ALLSTATE.COM, renewer=yarn, realUser=, issueDate=1502294518785, maxDate=1502899318785, sequenceNumber=4080301, masterKeyId=1928)
17/08/09 11:02:23 INFO knit.ApplicationMaster$: Launching container Container: [ContainerId: container_e105_1498411385005_148572_01_000002, NodeId: hostname1.allstate.com:8041, NodeHttpAddress: hostname1.allstate.com:8042, Resource: <memory:2048, vCores:1>, Priority: 0, Token: Token { kind: ContainerToken, service: 10.195.208.164:8041 }, ]
17/08/09 11:02:23 INFO knit.ApplicationMaster$: TOKEN ADDED: Kind: YARN_AM_RM_TOKEN, Service: 10.195.208.186:8030,10.195.208.187:8030, Ident: (org.apache.hadoop.yarn.security.AMRMTokenIdentifier@6cd7c572)
17/08/09 11:02:23 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_e105_1498411385005_148572_01_000002
17/08/09 11:02:23 INFO knit.ApplicationMaster$: TOKEN ADDED: Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:nameservice1, Ident: (token for jlord: HDFS_DELEGATION_TOKEN owner=jlord@AD.ALLSTATE.COM, renewer=yarn, realUser=, issueDate=1502294518785, maxDate=1502899318785, sequenceNumber=4080301, masterKeyId=1928)
17/08/09 11:02:23 INFO knit.ApplicationMaster$: Launching container Container: [ContainerId: container_e105_1498411385005_148572_01_000003, NodeId: hostname2.allstate.com:8041, NodeHttpAddress: hostname2.allstate.com:8042, Resource: <memory:2048, vCores:1>, Priority: 0, Token: Token { kind: ContainerToken, service: 10.195.102.92:8041 }, ]
17/08/09 11:02:23 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_e105_1498411385005_148572_01_000003
17/08/09 11:02:23 INFO knit.ApplicationMaster$: Container started container_e105_1498411385005_148572_01_000002
17/08/09 11:02:23 INFO knit.ApplicationMaster$: Container started container_e105_1498411385005_148572_01_000003
17/08/09 11:02:33 INFO knit.ApplicationMaster$: Container completed ContainerStatus: [ContainerId: container_e105_1498411385005_148572_01_000003, State: COMPLETE, Diagnostics: Exception from container-launch.
Container id: container_e105_1498411385005_148572_01_000003
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:601)
	at org.apache.hadoop.util.Shell.run(Shell.java:504)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:786)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:373)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Shell output: main : command provided 1
main : run as user is jlord
main : requested yarn user is jlord
Writing to tmp file /hadoop10/yarn/nm/nmPrivate/application_1498411385005_148572/container_e105_1498411385005_148572_01_000003/container_e105_1498411385005_148572_01_000003.pid.tmp


Container exited with a non-zero exit code 1
, ExitStatus: 1, ].getContainerId
17/08/09 11:02:37 INFO knit.ApplicationMaster$: Container completed ContainerStatus: [ContainerId: container_e105_1498411385005_148572_01_000002, State: COMPLETE, Diagnostics: Exception from container-launch.
Container id: container_e105_1498411385005_148572_01_000002
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:601)
	at org.apache.hadoop.util.Shell.run(Shell.java:504)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:786)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:373)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Shell output: main : command provided 1
main : run as user is jlord
main : requested yarn user is jlord
Writing to tmp file /hadoop09/yarn/nm/nmPrivate/application_1498411385005_148572/container_e105_1498411385005_148572_01_000002/container_e105_1498411385005_148572_01_000002.pid.tmp


Container exited with a non-zero exit code 1
, ExitStatus: 1, ].getContainerId
17/08/09 11:02:37 INFO impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
```

**Comment by martindurant** [comment]
Exit code 1 is, I think "not found", i.e., the python path $PYTHON_BIN is not executable. At least the container is, apparently, constructed correctly. The simplest problem might be that the environment was not correctly created - you could rm all of `knit/tmp_conda/miniconda/envs/` and try again. Maybe also clear the .knitDeps directory to be certain.
It may be worth introspecting the environment and files seen by the container by passing in simple commands

```
k = knit.Knit()
k.start('env', env='knit/tmp_conda/miniconda/envs/...')
k.logs()
```
with other commands like 'ls -l $PYTHON_BIN'...

(you need log aggregation to be active on your cluster for this to work)

**Comment by quartox** [comment]
Removing and rebuilding the environment didn't change the error.

Trying the code you supplied gave a different error. I am not sure how to parse it, specifically I can't tell what requests is trying to connect to (the edge node or the worker node?).

Command line output:

```
17/08/15 10:02:34 INFO knit.Client$: Staring Application Master
17/08/15 10:02:40 INFO hdfs.DFSClient: Created token for jlord: HDFS_DELEGATION_TOKEN owner=jlord@AD.ALLSTATE.COM, renewer=yarn, realUser=, issueDate=1502809359909, maxDate=1503414159909, sequenceNumber=4134543, masterKeyId=1934 on ha-hdfs:nameservice1
17/08/15 10:02:40 INFO knit.Utils$: Setting Replication Factor to: 3
17/08/15 10:02:40 INFO knit.Utils$: Attemping upload of /home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit/java_libs/knit-1.0-SNAPSHOT.jar to /user/jlord/.knitDeps
17/08/15 10:02:42 INFO knit.Utils$: Attemping upload of /home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit/tmp_conda/miniconda/envs/dask-35d2a1ee201208ae9fca6905fa88ea9e54557b58.zip to hdfs://nameservice1/user/jlord/.knitDeps
17/08/15 10:03:03 INFO knit.Client$: Submitting application application_1498411385005_167034
17/08/15 10:03:03 INFO impl.YarnClientImpl: Submitted application application_1498411385005_167034
Traceback (most recent call last):
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f9629fc4e48>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8088): Max retries exceeded with url: /ws/v1/cluster/apps/application_1498411385005_167034 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9629fc4e48>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "knit_test.py", line 5, in <module>
    k.logs()
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit/core.py", line 358, in logs
    return self.yarn_api.logs(self.app_id, shell=shell)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit/yarn_api.py", line 92, in logs
    running = self.status(app_id)['app']['state'] == 'RUNNING'
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit/yarn_api.py", line 166, in status
    r = requests.get(url)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8088): Max retries exceeded with url: /ws/v1/cluster/apps/application_1498411385005_167034 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9629fc4e48>: Failed to establish a new connection: [Errno 111] Connection refused',))
17/08/15 10:03:14 INFO impl.YarnClientImpl: Killed application application_1498411385005_167034
```


Hadoop logs:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.10.1-1.cdh5.10.1.p0.10/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/hadoop08/yarn/nm/filecache/46/knit-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17/08/15 10:03:11 INFO knit.ApplicationMaster$: Construct application master
17/08/15 10:03:13 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/15 10:03:13 INFO knit.ApplicationMaster$: Number of tokens: 2
17/08/15 10:03:13 INFO impl.NMClientAsyncImpl: Upper bound of the thread pool size is 500
17/08/15 10:03:13 INFO knit.ApplicationMaster$: Init application master
17/08/15 10:03:13 INFO knit.ApplicationMaster$: 0 containers still running, requesting 1
17/08/15 10:03:13 INFO knit.ApplicationMaster$: Add 1 containers
17/08/15 10:03:13 INFO knit.ApplicationMaster$: Request: 128 MB of RAM and 1 cores
17/08/15 10:03:13 INFO knit.ApplicationMaster$: Requested container resources: <memory:128, vCores:1>
17/08/15 10:03:13 INFO knit.ApplicationMaster$: Requested container ask: Capability[<memory:128, vCores:1>]Priority[0]
```

**Comment by martindurant** [comment]
@quartox , this seems to happen while querying the status of our application (i.e., submission seems to succeed). Can you try using the yarn CLI to see if it remains live and has containers (one for the master, others for workers)?
I see in the code that the call is explicitly to HTTP on the port that assumes HTTP - but yarn can be configured to be HTTPS only, normally on a different port (8090 versus 8088 in the default). This is a config in yarn-site.xml, and can easily be checked for.

**Comment by martindurant** [comment]
Perhaps fixed in https://github.com/dask/knit/pull/71/commits/d66dfe7cb463c953d00c5c5d289fb4dbc7b1ea4f ?

**Comment by quartox** [comment]
It might be an issue similar to the multiple name nodes, it looks like there are two resource managers, so maybe localhost won't work.

yarn-site.xml

```
  <property>
    <name>yarn.resourcemanager.webapp.address.rm1192</name>
    <value>hostname1.allstate.com:8088</value>
  </property>
  <property>
    <name>yarn.resourcemanager.webapp.https.address.rm1192</name>
    <value>hostname1.allstate.com:8090</value>
  </property>
  <property>
    <name>yarn.resourcemanager.webapp.address.rm1193</name>
    <value>hostname2.allstate.com:8088</value>
  </property>
  <property>
    <name>yarn.resourcemanager.webapp.https.address.rm1193</name>
    <value>hostname2.allstate.com:8090</value>
  </property>
```

**Comment by quartox** [comment]
The job is marked as failed almost immediately (10-20 seconds). I am finding this from using HUE, I will try to see if I can find more details from the yarn CLI.

**Comment by martindurant** [comment]
Can you please try with the latest commit, and passing in the values explicitly, trying the various combinations:

    DaskYARNCluster(pars={'yarn.http.policy': "HTTPS_ONLY", 'rm': 'hostname1.allstate.com',
        'rm_port_https': 8090, 'nn': ...})

or 

    DaskYARNCluster(pars={'yarn.http.policy': "HTTP_ONLY", 'rm': 'hostname1.allstate.com',
        'rm_port': 8088, 'nn': ...})

You are right, this is *not* the configuration I was [expecting](https://hadoop.apache.org/docs/r2.4.1/hadoop-yarn/hadoop-yarn-common/yarn-default.xml).

**Comment by quartox** [comment]
I am seeing the same problem using the most recent commit and explicitly passing the resource manager address. I have another angle to attack. Can I set the `$PYTHON_BIN` explicitly? If it is taken from `sys.executable` that is pointing to an executable that isn't available on the hadoop cluster and is an easy fix.

Nevermind, found it in the docs.

**Comment by quartox** [comment]
Explicit `PYTHON_BIN` didn't fix it either.

**Comment by martindurant** [comment]
Yes, you could dive into the [application master](https://github.com/martindurant/knit/blob/more/knit_jvm/src/main/scala/io/continuum/knit/ApplicationMaster.scala#L189) (remember to rebuild the jar with maven if you edit), but of course the command as it is now has the full path to python already.

What you really want to do, though, is investigate the environment available to the worker container: variables, files, and whether it can read/write to hdfs.

**Comment by martindurant** [comment]
@quartox  for example, I get an environment like the following (no kerb on this one), noting that PWD is the container dir within LOCAL_DIRS, and PYTHON_BIN is a path relative to this - looking at the location on the disc, I see it is a link to the unzipped environment. Given that CONTAINER_ID is also in the env, it would be reasonable to construct the container command using environment variables, to use an absolute path rather than relative, or simply add the conda bin/ directory to PATH.

```
{
  "CLASSPATH": "/opt/hadoop/etc/hadoop:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/hdfs/*:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/yarn/*:/opt/hadoop/share/hadoop/yarn/lib/*:/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1502896932869_0001/container_1502896932869_0001_01_000002/*",
  "CONDA_PREFIX": "./PYTHON_DIR/dask-35d2a1ee201208ae9fca6905fa88ea9e54557b58/",
  "CONTAINER_ID": "container_1502896932869_0001_01_000002",
  "HADOOP_CLASSPATH": "/contrib/capacity-scheduler/*.jar:/contrib/capacity-scheduler/*.jar",
  "HADOOP_CLIENT_OPTS": "-Xmx512m -Xmx512m ",
  "HADOOP_COMMON_HOME": "/opt/hadoop",
  "HADOOP_CONF_DIR": "/opt/hadoop/etc/hadoop",
  "HADOOP_DATANODE_OPTS": "-Dhadoop.security.logger=ERROR,RFAS -Dhadoop.security.logger=ERROR,RFAS ",
  "HADOOP_HDFS_HOME": "/opt/hadoop",
  "HADOOP_IDENT_STRING": "root",
  "HADOOP_MAPRED_HOME": "/opt/hadoop",
  "HADOOP_NAMENODE_OPTS": "-Dhadoop.security.logger=INFO,RFAS -Dhdfs.audit.logger=INFO,NullAppender -Dhadoop.security.logger=INFO,RFAS -Dhdfs.audit.logger=INFO,NullAppender ",
  "HADOOP_NFS3_OPTS": "",
  "HADOOP_OPTS": " -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/opt/hadoop/logs -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/opt/hadoop -Dhadoop.id.str=root -Dhadoop.root.logger=INFO,console -Djava.library.path=/opt/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Stack=true -Dhadoop.log.dir=/opt/hadoop/logs -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/opt/hadoop -Dhadoop.id.str=root -Dhadoop.root.logger=INFO,console -Djava.library.path=/opt/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true",
  "HADOOP_PID_DIR": "",
  "HADOOP_PORTMAP_OPTS": "-Xmx512m -Xmx512m ",
  "HADOOP_PREFIX": "/opt/hadoop",
  "HADOOP_SECONDARYNAMENODE_OPTS": "-Dhadoop.security.logger=INFO,RFAS -Dhdfs.audit.logger=INFO,NullAppender -Dhadoop.security.logger=INFO,RFAS -Dhdfs.audit.logger=INFO,NullAppender ",
  "HADOOP_SECURE_DN_PID_DIR": "",
  "HADOOP_SECURE_DN_USER": "",
  "HADOOP_TOKEN_FILE_LOCATION": "/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1502896932869_0001/container_1502896932869_0001_01_000002/container_tokens",
  "HADOOP_YARN_HOME": "/opt/hadoop",
  "HADOOP_YARN_USER": "yarn",
  "HOME": "/home/",
  "JAVA_HOME": "/opt/conda",
  "JVM_PID": "2416",
  "LC_ALL": "C.UTF-8",
  "LD_LIBRARY_PATH": ":/opt/hadoop/lib/native:/opt/hadoop/lib/native",
  "LOCAL_DIRS": "/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1502896932869_0001",
  "LOGNAME": "root",
  "LOG_DIRS": "/opt/hadoop/logs/userlogs/application_1502896932869_0001/container_1502896932869_0001_01_000002",
  "MAIL": "/var/mail/root",
  "MALLOC_ARENA_MAX": "4",
  "NLSPATH": "/usr/dt/lib/nls/msg/%L/%N.cat",
  "NM_AUX_SERVICE_mapreduce_shuffle": "AAA0+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\r\n",
  "NM_HOST": "93bdf75c053b",
  "NM_HTTP_PORT": "8042",
  "NM_PORT": "39393",
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games",
  "PWD": "/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1502896932869_0001/container_1502896932869_0001_01_000002",
  "PYTHON_BIN": "./PYTHON_DIR/dask-35d2a1ee201208ae9fca6905fa88ea9e54557b58/bin/python",
  "SHELL": "/bin/bash",
  "SHLVL": "4",
  "SSH_CLIENT": "127.0.0.1 47868 22",
  "SSH_CONNECTION": "127.0.0.1 47868 127.0.0.1 22",
  "USER": "root",
  "XFILESEARCHPATH": "/usr/dt/app-defaults/%L/Dt",
  "YARN_CONF_DIR": "/opt/hadoop/etc/hadoop",
  "YARN_IDENT_STRING": "root",
  "YARN_LOGFILE": "yarn-root-nodemanager-93bdf75c053b.log",
  "YARN_NICENESS": "0",
  "YARN_ROOT_LOGGER": "INFO,RFA",
  "_": "./PYTHON_DIR/dask-35d2a1ee201208ae9fca6905fa88ea9e54557b58/bin/python"
}

```

**Comment by quartox** [comment]
#88 and #89 has resolved this issue

**Comment by martindurant** [comment]
Hurray!
